### ISSUE TITLE
设置代理的问题

### ISSUE THREAD

**Issue by xiao-rao** [admin4j/common-http#6]
在暴露的接口里，没有找到可以设置代理的方法，请问怎么设置呢

**Comment by andanyoung** [comment]
查看下这个类`HttpConfig.ProxyConfig`

在配置文件(application.yml)中配置
```
admin4j:
  http:
    proxy:
      ......
```
